In [74]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

# Scikit-learn imports
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

# Gradient Boosting libraries
from catboost import CatBoostRegressor
from xgboost import XGBRegressor

models = {
    "LinearRegression": LinearRegression(),
    "Ridge": Ridge(),
    "Lasso": Lasso(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "RandomForestRegressor": RandomForestRegressor(),
    "XGBRegressor": XGBRegressor(),
    "CatBoostRegressor": CatBoostRegressor(verbose=0),
    "AdaBoostRegressor": AdaBoostRegressor(),
}

model_List = []
r2_list = []

In [75]:
df = pd.read_csv(r"C:\mlproject\notepad\data\StudentsPerformance.csv")

In [76]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [77]:
X = df.drop('math score', axis=1)

In [78]:
X

,gender,race/ethnicity,parental level of education,lunch,test preparation course,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75
...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,99,95
996,male,group C,high school,free/reduced,none,55,55
997,female,group C,high school,free/reduced,completed,71,65
998,female,group D,some college,standard,completed,78,77
999,female,group D,some college,free/reduced,none,86,86

In [79]:
y=df['math score']

In [80]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

num_features = ["reading score", "writing score"]

cat_features = [
    "gender",
    "race/ethnicity",
    "parental level of education",
    "lunch",
    "test preparation course"
]

preprocessor = ColumnTransformer(
    [
        ("cat", OneHotEncoder(), cat_features),
        ("num", StandardScaler(), num_features)
    ]
)

In [81]:
X = preprocessor.fit_transform(X)

In [82]:
X.shape

(1000, 19)

In [83]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape

((800, 19), (200, 19))

In [84]:
def evaluate_model(true,predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mse)
    r2 = r2_score(true, predicted)
    return mae, mse, rmse, r2

In [85]:
models = {
    "LinearRegression":LinearRegression(),
    "Ridge":Ridge(),
    "Lasso":Lasso(),
    "K-Neighbors Regressor":KNeighborsRegressor(),
    "RandomForestRegressor":RandomForestRegressor(),
    "XGBRegressor":XGBRegressor(),
    "CatBoostRegressor":CatBoostRegressor(verbose=0),
    "AdaBoostRegressor":AdaBoostRegressor(),
}
model_List=[]
r2_list =[]
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    model_train_mae, model_train_mse, model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)
    model_test_mae, model_test_mse, model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)
    print(list(models.keys())[i])
    model_List.append(list(models.keys())[i])
    print("model performance on training set")
    print("-Root Mean Squared Error:{:.4f} ".format(model_train_rmse))
    print("-Mean Absolute Error:{:.4f} ".format(  model_train_mae))
    print("r2_score: {:.4f} ".format( model_train_r2))
    
    print("-"*50)
    print("model performance on test set")
    print("-Root Mean Squared Error:{:.4f} ".format(model_test_rmse))
    print("-Mean Absolute Error:{:.4f} ".format(  model_test_mae))
    print("r2_score: {:.4f} ".format( model_test_r2))
    r2_list.append(model_test_r2)

LinearRegression
model performance on training set
-Root Mean Squared Error:5.3231
-Mean Absolute Error:4.2667
r2_score: 0.8743
--------------------------------------------------
model performance on test set
-Root Mean Squared Error:5.3940
-Mean Absolute Error:4.2148
r2_score: 0.8804
Ridge
model performance on training set
-Root Mean Squared Error:5.3233
-Mean Absolute Error:4.2650
r2_score: 0.8743
--------------------------------------------------
model performance on test set
-Root Mean Squared Error:5.3904
-Mean Absolute Error:4.2111
r2_score: 0.8806
Lasso
model performance on training set
-Root Mean Squared Error:6.5938
-Mean Absolute Error:5.2063
r2_score: 0.8071
--------------------------------------------------
model performance on test set
-Root Mean Squared Error:6.5197
-Mean Absolute Error:5.1579
r2_score: 0.8253
K-Neighbors Regressor
model performance on training set
-Root Mean Squared Error:5.7088
-Mean Absolute Error:4.5177
r2_score: 0.8554
--------------------------------------------------
model performance on test set
-Root Mean Squared Error:7.2494
-Mean Absolute Error:5.6090
r2_score: 0.7840
RandomForestRegressor
model performance on training set
-Root Mean Squared Error:2.3023
-Mean Absolute Error:1.8370
r2_score: 0.9765
--------------------------------------------------
model performance on test set
-Root Mean Squared Error:6.0643
-Mean Absolute Error:4.7584
r2_score: 0.8489
XGBRegressor
model performance on training set
-Root Mean Squared Error:1.0073
-Mean Absolute Error:0.6875
r2_score: 0.9955
--------------------------------------------------
model performance on test set
-Root Mean Squared Error:6.4733
-Mean Absolute Error:5.0577
r2_score: 0.8278
CatBoostRegressor
model performance on training set
-Root Mean Squared Error:3.0427
-Mean Absolute Error:2.4054
r2_score: 0.9589
--------------------------------------------------
model performance on test set
-Root Mean Squared Error:6.0086
-Mean Absolute Error:4.6125
r2_score: 0.8516
AdaBoostRegressor
model performance on training set
-Root Mean Squared Error:5.8448
-Mean Absolute Error:4.7873
r2_score: 0.8485
--------------------------------------------------
model performance on test set
-Root Mean Squared Error:6.1928
-Mean Absolute Error:4.8392
r2_score: 0.8424

In [86]:
pd.DataFrame({"Model":model_List,"R2_Score":r2_list}).sort_values(by="R2_Score",ascending=False)

                   Model  R2_Score
1                  Ridge  0.880593
0       LinearRegression  0.880433
6      CatBoostRegressor  0.851632
4  RandomForestRegressor  0.848872
7      AdaBoostRegressor  0.842399
5           XGBRegressor  0.827797
2                  Lasso  0.825320
3  K-Neighbors Regressor  0.784030